import type { Problem } from "../../mockApi";

const iso = (daysAgo: number) => new Date(Date.now() - 1000 * 60 * 60 * 24 * daysAgo).toISOString();

/** spec プレビュー用の固定 Problem 群（store に依存しない決め打ちデータ）。 */
export const sampleProblems: Problem[] = [
  {
    id: "p-career",
    title: "転職すべきか迷っている",
    summary:
      "今の職場で成長実感が薄く転職を検討しているが、辞めることへの罪悪感と収入の不安で踏み切れない。",
    theme: "仕事・キャリア",
    tags: ["転職", "成長実感", "罪悪感"],
    status: "open",
    mentionCount: 3,
    plans: [],
    createdAt: iso(28),
    lastMentionedAt: iso(3),
    resolvedAt: null,
    shelvedAt: null,
    mentions: [
      {
        id: "m-career-1",
        sessionId: "s-1001",
        dumpId: "s-1001",
        createdAt: iso(28),
        statement: "今の仕事で成長している実感がなく、転職を考え始めた。",
        excerpt: "このままここにいて成長できるのか不安で…",
        affect: { label: "停滞感", valence: "negative", intensity: 0.5 },
        proposedTheme: "仕事・キャリア",
        proposedTags: ["転職", "成長実感"],
        problemId: "p-career",
        groupingConfidence: null,
      },
      {
        id: "m-career-2",
        sessionId: "s-1014",
        dumpId: "s-1014",
        createdAt: iso(12),
        statement: "辞めたい気持ちはあるが、世話になった人を裏切る罪悪感がある。",
        excerpt: "辞めたら今のチームに申し訳ないって思っちゃう",
        affect: { label: "罪悪感", valence: "negative", intensity: 0.72 },
        proposedTheme: "仕事・キャリア",
        proposedTags: ["罪悪感"],
        problemId: "p-career",
        groupingConfidence: 0.86,
      },
      {
        id: "m-career-3",
        sessionId: "s-1022",
        dumpId: "s-1022",
        createdAt: iso(3),
        statement: "転職サイトに登録だけしてみた。少し前に進んだ感覚がある。",
        excerpt: "とりあえず登録だけしてみたら気が楽になった",
        affect: { label: "前向き", valence: "positive", intensity: 0.4 },
        proposedTheme: "仕事・キャリア",
        proposedTags: ["転職", "行動"],
        problemId: "p-career",
        groupingConfidence: 0.9,
      },
    ],
  },
  {
    id: "p-sleep",
    title: "夜うまく眠れない",
    summary: "考えごとで寝つきが悪く、翌日の集中力が落ちている。睡眠リズムを立て直したい。",
    theme: "心と体",
    tags: ["睡眠", "疲労"],
    status: "open",
    mentionCount: 2,
    plans: [
      {
        title: "睡眠リズム立て直しプラン",
        steps: ["就寝1時間前にスマホを置く", "起床時間を固定する", "朝に5分散歩する"],
      },
    ],
    createdAt: iso(20),
    lastMentionedAt: iso(6),
    resolvedAt: null,
    shelvedAt: null,
    mentions: [
      {
        id: "m-sleep-1",
        sessionId: "s-1008",
        dumpId: "s-1008",
        createdAt: iso(20),
        statement: "夜になると考えごとが止まらず寝つけない。",
        excerpt: "布団に入っても頭が冴えちゃって",
        affect: { label: "焦り", valence: "negative", intensity: 0.6 },
        proposedTheme: "心と体",
        proposedTags: ["睡眠"],
        problemId: "p-sleep",
        groupingConfidence: null,
      },
      {
        id: "m-sleep-2",
        sessionId: "s-1019",
        dumpId: "s-1019",
        createdAt: iso(6),
        statement: "寝不足が続いて日中ぼーっとする時間が増えた。",
        excerpt: "最近ずっと眠くて仕事に集中できない",
        affect: { label: "疲労", valence: "negative", intensity: 0.68 },
        proposedTheme: "心と体",
        proposedTags: ["睡眠", "疲労"],
        problemId: "p-sleep",
        groupingConfidence: 0.82,
      },
    ],
  },
  {
    id: "p-habit",
    title: "運動習慣が続かない",
    summary: "運動が三日坊主だったが、朝の散歩を習慣化できて解決した。",
    theme: "日常・生活",
    tags: ["運動", "習慣"],
    status: "resolved",
    mentionCount: 1,
    plans: [],
    createdAt: iso(33),
    lastMentionedAt: iso(33),
    resolvedAt: iso(15),
    shelvedAt: null,
    mentions: [
      {
        id: "m-habit-1",
        sessionId: "s-1006",
        dumpId: "s-1006",
        createdAt: iso(33),
        statement: "運動しようと思っても三日坊主で続かない。",
        excerpt: "何度やっても続かなくて自己嫌悪",
        affect: { label: "自己嫌悪", valence: "negative", intensity: 0.45 },
        proposedTheme: "日常・生活",
        proposedTags: ["運動", "習慣"],
        problemId: "p-habit",
        groupingConfidence: null,
      },
    ],
  },
];
