#!/usr/bin/env python3
"""通報ステップの「何をするか / どう見せるか」を決める純関数 (Issue #507)。

判定は 2 段:
    1. plan_action()  — Issue をどうするか (decide.py を土台に、**一覧が引けなかった**
       という第 3 の状態を足したもの)
    2. step_verdict() — 通報に失敗したとき step を赤にするか

なぜ純関数に切り出すか:
    「通報が失敗したか」「その失敗で run を赤にしてよいか」は **判定** であって
    シェルの副作用の順番ではない。ここに置いてテストで固定する
    (cicd/CLAUDE.md「判定ロジックをシェルや workflow の中に埋めない」)。
"""

# #507 の原因 (2026-08-17 の deploy 3 run / 32050157344・32048671609・32048667300):
#   デプロイ本体が全部緑なのに通報ステップだけが **1 行も出力を残さず exit 1** し、
#   run 全体を赤にした。旧実装は open Issue の一覧を `EXISTING=$(gh issue list ...)`
#   というコマンド置換で受けており、runner 既定の `bash -e` 下では gh が非ゼロを返した
#   瞬間に step が死ぬ。しかもその gh 呼び出しは標準エラーを /dev/null へ捨てていたので、
#   **何が失敗したのかがログに 1 文字も残らなかった**。2026-08-21 の deploy は同じコードで
#   緑に戻っており、gh の非ゼロは一過性だったが、**一過性の失敗を無言の赤に変換する**
#   構造そのものが欠陥。

from __future__ import annotations

import sys
from pathlib import Path
from typing import NamedTuple, Sequence

sys.path.insert(0, str(Path(__file__).resolve().parent))

from decide import APPEND, CLOSE, NOOP, OPEN, decide  # noqa: E402

__all__ = [
    "APPEND",
    "CLOSE",
    "NOOP",
    "OPEN",
    "FAILURE_COMMENT_MARKER",
    "RECOVERY_COMMENT_MARKER",
    "StepVerdict",
    "classify_label_create",
    "effective_status",
    "failure_comment",
    "issue_body",
    "issue_title",
    "plan_action",
    "recovery_comment",
    "select_issue_number",
    "step_verdict",
]

# 「🔴 まだ落ちています」は **状況ページが再発時刻を測る目印**。Issue の created_at は
# 初回の障害で固定されるため、閉じ損ねた Issue に再発が追記された場合、この追記の時刻で
# しか「今も落ちている」が分からない。**変えたら cicd/scripts/status-page/product_status.py
# の FAILURE_COMMENT_MARKER も直すこと** (PR #281)。ズレは test_notify_rules.py が落とす。
FAILURE_COMMENT_MARKER = "🔴 まだ落ちています"
RECOVERY_COMMENT_MARKER = "✅ 復旧しました。"

_ATTRIBUTION = "---\n_Generated by [Claude Code](https://claude.ai/code)_"


def effective_status(job_status: str, cancelled_is_failure: bool) -> str:
    """cancelled を呼び出し元の意図で success / failure のどちらかに畳む。

    cancelled はタイムアウト (= 障害) のことも concurrency による自己中断 (= 正常)
    のこともあり、**呼び出し元しか区別できない** (decide.py の docstring と同じ前提)。
    """
    status = job_status.strip().lower()
    if status == "cancelled":
        return "failure" if cancelled_is_failure else "success"
    if status in ("success", "failure"):
        return status
    # 未知の状態を「異常なし」に丸めない。報告側に寄せる。
    return "failure"


def plan_action(
    job_status: str,
    work_ran: bool,
    cancelled_is_failure: bool,
    *,
    lookup_ok: bool,
    has_open_issue: bool,
) -> str:
    """Issue に対して何をするかを返す (open / append / close / noop)。

    lookup_ok=True のときは decide.decide() をそのまま使う (既存の判定は変えない)。

    lookup_ok=False は **「open な Issue があるか分からない」** という第 3 の状態で、
    旧実装には存在しなかった (一覧が引けない = そのまま無言で死ぬ、が #507)。
    ここでの倒し方は非対称にする:

      - job が失敗側 → OPEN。一覧が引けないだけで通報しないと、**落ちたのに Issue が
        立たない** (Issue #507 の「逆向きの障害」)。重複 Issue は目に見えて安いが、
        無通報は「黙っている = 落ちていない」という前提ごと壊すので高い (ADR 0035 D2)。
      - job が成功側 → NOOP。失うのは「open Issue を閉じる」だけで、閉じ損ねた Issue は
        open のまま残る = 状況ページは**赤に倒れる** (偽の緑にはならない)。次に緑で
        通った run が閉じ直す。
    """
    if lookup_ok:
        return decide(job_status, work_ran, cancelled_is_failure, has_open_issue)
    if effective_status(job_status, cancelled_is_failure) == "failure":
        return OPEN
    return NOOP


def select_issue_number(issues: Sequence[dict], title: str) -> int | None:
    """タイトル**完全一致**の Issue 番号を、渡された順の先頭から 1 件返す。

    部分一致にすると別 workflow の Issue に相乗りする (旧実装の jq も完全一致だった)。
    jq 式ではなくここに置いたのは、シェルの中では「一致しなかった」と
    「jq 自体が壊れた」が同じ空文字列になり、区別できないため。
    """
    for issue in issues:
        if issue.get("title") == title:
            number = issue.get("number")
            if isinstance(number, int):
                return number
    return None


def classify_label_create(returncode: int, stderr: str) -> str:
    """`gh label create` の結果を created / already-exists / error に分ける。

    ラベルが既にあるときの非ゼロは正常運用なので黙る。それ以外の非ゼロ (権限不足・
    API 障害) まで同じ形で潰すと、**ラベルが付かない Issue** が立ち、状況ページの
    ci-failure 集計から静かに漏れる。旧実装はこの 2 つを区別していなかった。
    """
    if returncode == 0:
        return "created"
    if "already exists" in stderr.lower():
        return "already-exists"
    return "error"


class StepVerdict(NamedTuple):
    """通報ステップ自身の後始末。fail_step が True のときだけ step を赤にする。"""

    fail_step: bool
    message: str


def step_verdict(
    job_status: str,
    cancelled_is_failure: bool,
    failures: Sequence[str],
) -> StepVerdict:
    """通報に失敗したとき step を赤にするかを決める (#507 の設計判断)。

    2 つの要求が衝突する:
      (a) 通報の失敗を見えなくしない — 潰すと「落ちたのに Issue が立たない」に気づけない
      (b) デプロイの緑を通報の失敗で赤くしない — run の色が「dev に届いたか」を
          答えなくなり、状況ページ・戦況図の一次判定を汚す (#507 の実害)

    両立させるため、**「見せる」と「赤にする」を分ける**:
      - 失敗は job の成否によらず必ず `::error::` 注釈 + step summary に出す (= (a))
      - exit code を非ゼロにするのは **その失敗が障害を隠すとき**、つまり job が
        失敗側のときだけ。job が失敗側なら run はもともと赤なので、赤を足しても
        「デプロイの緑」は汚れない (= (b))

    job が成功側で通報に失敗した場合に失うのは「open Issue を閉じる」だけで、
    その取りこぼしは **Issue が open のまま残る = 状況ページが赤に倒れる** という
    形で自分で見える (偽の緑にならない)。次に緑で通った run が閉じ直す。
    """
    if not failures:
        return StepVerdict(False, "通報は完了した")
    detail = " / ".join(failures)
    if effective_status(job_status, cancelled_is_failure) == "failure":
        return StepVerdict(
            True,
            f"job が失敗した回の通報に失敗したため step も赤にする ({detail})",
        )
    return StepVerdict(
        False,
        "通報に失敗したが job は成功しているため step は赤にしない "
        f"(閉じ損ねた Issue は open のまま残り、次の緑の run が閉じ直す): {detail}",
    )


def issue_title(workflow: str) -> str:
    return f"[ci-failure] {workflow} が落ちている"


def _trailer(run_url: str, sha: str, ref: str) -> str:
    return f"- run: {run_url}\n- commit: `{sha}` ({ref})\n\n{_ATTRIBUTION}"


def failure_comment(run_url: str, sha: str, ref: str) -> str:
    return f"{FAILURE_COMMENT_MARKER}。\n\n{_trailer(run_url, sha, ref)}"


def recovery_comment(run_url: str, sha: str, ref: str) -> str:
    return f"{RECOVERY_COMMENT_MARKER}\n\n{_trailer(run_url, sha, ref)}"


def issue_body(what: str, workflow: str, run_url: str, sha: str, ref: str) -> str:
    return (
        f"{what}\n\n"
        "| | |\n| --- | --- |\n"
        f"| workflow | `{workflow}` |\n"
        f"| run | {run_url} |\n"
        f"| commit | `{sha}` |\n"
        f"| ref | `{ref}` |\n\n"
        "**この Issue は落ちた workflow 自身が立てています** (ADR 0035 D2)。\n"
        "次に同じ workflow が緑になれば自動で閉じます。**手で閉じないでください** —\n"
        "閉じても直っていなければ、次の失敗でまた立ちます。\n\n"
        f"{_ATTRIBUTION}"
    )
